version: "3.9"

services:
  app:
    container_name: club_serveur
    build:
      context: ./takeoff
      dockerfile: ./app/Dockerfile
    network_mode: host

  script:
    build:
      context: ./takeoff
      dockerfile: ./script/Dockerfile
    network_mode: host

  mongodb:
    image: mongo:4.2.13-bionic
    container_name: club_mongodb
    restart: unless-stopped
    mem_limit: 3g
    network_mode: host

volumes:
  club_mongodb_data:
    driver: local
    name: club_mongodb_data
  club_server_data:
    driver: local
    name: club_server_data
